
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."bahasa" (
    "id_bahasa" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nama_bahasa" "text" NOT NULL
);

ALTER TABLE "public"."bahasa" OWNER TO "postgres";

ALTER TABLE "public"."bahasa" ALTER COLUMN "id_bahasa" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bahasa_id_bahasa_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."feedback" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "message" "text"
);

ALTER TABLE "public"."feedback" OWNER TO "postgres";

ALTER TABLE "public"."feedback" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feedback_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."kelas_kata" (
    "id_kelas_kata" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nama" character varying NOT NULL,
    "singkatan" character varying
);

ALTER TABLE "public"."kelas_kata" OWNER TO "postgres";

ALTER TABLE "public"."kelas_kata" ALTER COLUMN "id_kelas_kata" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."kelas_kata_id_kelas_kata_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."kosakata" (
    "id_kosakata" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "kata" "text",
    "lafal" character varying,
    "arti" "text",
    "contoh_asal" "text",
    "contoh_terjemahan" "text",
    "id_kelas_kata" bigint,
    "id_bahasa" bigint
);

ALTER TABLE "public"."kosakata" OWNER TO "postgres";

ALTER TABLE "public"."kosakata" ALTER COLUMN "id_kosakata" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."kosakata_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."bahasa"
    ADD CONSTRAINT "bahasa_pkey" PRIMARY KEY ("id_bahasa");

ALTER TABLE ONLY "public"."feedback"
    ADD CONSTRAINT "feedback_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."kelas_kata"
    ADD CONSTRAINT "kelas_kata_pkey" PRIMARY KEY ("id_kelas_kata");

ALTER TABLE ONLY "public"."kosakata"
    ADD CONSTRAINT "kosakata_pkey" PRIMARY KEY ("id_kosakata");

CREATE INDEX "idx_kosakata_kata_id_bahasa" ON "public"."kosakata" USING "btree" ("kata", "id_bahasa");

ALTER TABLE ONLY "public"."kosakata"
    ADD CONSTRAINT "kosakata_id_bahasa_fkey" FOREIGN KEY ("id_bahasa") REFERENCES "public"."bahasa"("id_bahasa");

ALTER TABLE ONLY "public"."kosakata"
    ADD CONSTRAINT "kosakata_id_kelas_kata_fkey" FOREIGN KEY ("id_kelas_kata") REFERENCES "public"."kelas_kata"("id_kelas_kata");

CREATE POLICY "Enable insert for authenticated users only" ON "public"."feedback" FOR INSERT TO "anon" WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."kosakata" FOR SELECT TO "anon" USING (true);
CREATE POLICY "Enable read access for all users" ON "public"."kelas_kata" FOR SELECT TO "anon" USING (true);

ALTER TABLE "public"."bahasa" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."feedback" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."kelas_kata" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."kosakata" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."bahasa" TO "anon";
GRANT ALL ON TABLE "public"."bahasa" TO "authenticated";
GRANT ALL ON TABLE "public"."bahasa" TO "service_role";

GRANT ALL ON SEQUENCE "public"."bahasa_id_bahasa_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bahasa_id_bahasa_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bahasa_id_bahasa_seq" TO "service_role";

GRANT ALL ON TABLE "public"."feedback" TO "anon";
GRANT ALL ON TABLE "public"."feedback" TO "authenticated";
GRANT ALL ON TABLE "public"."feedback" TO "service_role";

GRANT ALL ON SEQUENCE "public"."feedback_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."feedback_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."feedback_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."kelas_kata" TO "anon";
GRANT ALL ON TABLE "public"."kelas_kata" TO "authenticated";
GRANT ALL ON TABLE "public"."kelas_kata" TO "service_role";

GRANT ALL ON SEQUENCE "public"."kelas_kata_id_kelas_kata_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."kelas_kata_id_kelas_kata_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."kelas_kata_id_kelas_kata_seq" TO "service_role";

GRANT ALL ON TABLE "public"."kosakata" TO "anon";
GRANT ALL ON TABLE "public"."kosakata" TO "authenticated";
GRANT ALL ON TABLE "public"."kosakata" TO "service_role";

GRANT ALL ON SEQUENCE "public"."kosakata_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."kosakata_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."kosakata_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
