
-- SCHEMA DATABASE UNTUK DIJALANKAN DI SUPABASE


-- Tabel Feedback
create table
  public.feedback (
    id bigint generated by default as identity not null,
    created_at timestamp
with time zone null default
(now
() at time zone 'utc'::text),
    message text not null,
    constraint feedback_pkey primary key
(id)
  ) tablespace pg_default;



-- Tabel Kata Indonesia
create table
  public.kata_indonesia (
    id bigint generated by default as identity not null,
    created_at timestamp
with time zone null default now
(),
    kata character varying null,
    contoh text null,
    kata_mooi_id bigint null,
    constraint kata_indonesia_pkey primary key
(id),
    constraint kata_indonesia_kata_mooi_id_fkey foreign key
(kata_mooi_id) references kata_mooi
(id) on
delete cascade
  ) tablespace pg_default;


-- Tabel Kata Mooi
create table
  public.kata_mooi (
    id bigint generated by default as identity not null,
    created_at timestamp
with time zone null default
(now
() at time zone 'utc'::text),
    kata character varying null,
    lafal character varying null,
    arti character varying null,
    contoh text null,
    kelas_kata_id bigint null,
    constraint kata_mooi_pkey primary key
(id),
    constraint kata_mooi_kelas_kata_id_fkey foreign key
(kelas_kata_id) references kelas_kata
(id) on
delete cascade
  ) tablespace pg_default;


-- Tabel Kelas Kata
create table
  public.kelas_kata (
    id bigint generated by default as identity not null,
    created_at timestamp
with time zone null default now
(),
    nama character varying null,
    singkatan character varying null,
    constraint kelas_kata_pkey primary key
(id)
  ) tablespace pg_default;